[package]
name = "harnas-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = "0.28"
humantime = "2.1"
notify = "6.1"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

